bind 0.0.0.0
protected-mode yes
port 6379
timeout 0
tcp-keepalive 60
unixsocket /run/mini-ocs/redis.sock
unixsocketperm 777

appendonly yes
appendfsync everysec
save 60 1000

loglevel notice
logfile ""
